const LOCAL_AI_PROVIDER = 'local-ai'
const LOCAL_AI_RUNTIME_MODE = 'sidecar'
const LOCAL_AI_RUNTIME = 'idena-local-runtime'
const LOCAL_AI_RUNTIME_BACKEND = 'ollama-direct'
const LOCAL_AI_REASONER_BACKEND = 'local-reasoner'
const LOCAL_AI_VISION_BACKEND = 'local-vision'
const LOCAL_AI_RUNTIME_FAMILY = 'local-reasoner'
const LOCAL_AI_DEFAULT_BASE_URL = 'http://127.0.0.1:11434'
const LOCAL_AI_DEFAULT_MODEL = ''
const LOCAL_AI_DEFAULT_VISION_MODEL = ''
const LOCAL_AI_PUBLIC_MODEL_ID = 'Idena-text-v1'
const LOCAL_AI_PUBLIC_VISION_ID = 'Idena-multimodal-v1'
const LOCAL_AI_ADAPTER_STRATEGY = 'lora-first'
const LOCAL_AI_TRAINING_POLICY = 'approved-post-consensus-only'
const LOCAL_AI_CONTRACT_VERSION = 'idena-local/v1'
const LOCAL_AI_BASE_MODEL_ID =
  'idena-local:Idena-multimodal-v1:adapter-lora-first-v1'

module.exports = {
  LOCAL_AI_PROVIDER,
  LOCAL_AI_RUNTIME_MODE,
  LOCAL_AI_RUNTIME,
  LOCAL_AI_RUNTIME_BACKEND,
  LOCAL_AI_REASONER_BACKEND,
  LOCAL_AI_VISION_BACKEND,
  LOCAL_AI_RUNTIME_FAMILY,
  LOCAL_AI_DEFAULT_BASE_URL,
  LOCAL_AI_DEFAULT_MODEL,
  LOCAL_AI_DEFAULT_VISION_MODEL,
  LOCAL_AI_PUBLIC_MODEL_ID,
  LOCAL_AI_PUBLIC_VISION_ID,
  LOCAL_AI_ADAPTER_STRATEGY,
  LOCAL_AI_TRAINING_POLICY,
  LOCAL_AI_CONTRACT_VERSION,
  LOCAL_AI_BASE_MODEL_ID,
}
